### PR TITLE
breaking: refactor how conflict metrics and logs are done

### PR DESCRIPTION
**Pull request by darahayes**
The most important file to look at is `voyagerResolvers.ts`. This PR makes the logging and metrics recording of conflicts super simple. If metrics and/or audit logs are enabled by the user, then all user resolvers are wrapped using this `voyagerResolvers.ts` file.

It's very simple: simply check the `result` that came back from the user's resolver and if a conflict object was returned then we can log the conflict and record the metrics.

- [x] `npm test` passes
- [x] tests are included
- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](../doc/guides/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by wtrocki** [comment]
@darahayes I approved it with the meaning that I checked code and also verified it locally. 
However I did not verified it in context of wider audit log stuff. Leaving decision for @aliok but I'm happy with the changes.

**Comment by aliok** [comment]
Looks good and much simpler. I will give it a try now.

**Comment by aliok** [comment]
Didn't see `CONFLICT` log in the audit logs when there's a conflict. Will check it

**Comment by darahayes** [comment]
@aliok that happens to me several times a day 😃 Thanks for the review!

**Comment by wtrocki** [comment]
Wow. Thanks for merging. Now we can release another RC

**Pull request merged**
