### PR TITLE
Fix voyager-subscriptions version in examples

### PR DESCRIPTION
**Pull request by b1zzu**
### Description

Because version `0.5.1` doesn't exist for `@aerogear/voyager-subscriptions` we should use the version `0.5.2-dev.1` until the next release.

##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](../doc/guides/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by wtrocki** [comment]
We recommend to use lerna bootstrap or simply npm run bootstrap to get this working on local machine. Examples are designed to work with the unrelased versions from master but maybe this stopped working now

**Comment by darahayes** [comment]
@b1zzu can you try running `npm run clean` from the top level directory and then run `npm run bootstrap.` Will the example server work?

I have this example merged but the package isn't released yet but it will be in the next day or so.

**Comment by b1zzu** [comment]
Using `npm run bootstrap` works. But I was testing to deploy of the example app in OpenShift using the data sync template [1] , and because the template is using S2I in order to build the example it doesn't work in that context. (S2I use npm install)

1. https://github.com/aerogear/datasync-deployment/blob/master/openshift/datasync-http.yml

**Comment by darahayes** [comment]
@b1zzu thanks for that info. I'm happy to merge this PR for the time being if it helps unblock any work you are doing on the openshift side. 👍

**Comment by darahayes** [comment]
@b1zzu could you update it to the latest version? It's `0.6.1-dev-1`. That will be the proper version number once it's released. The 0.5.1 was an accidental publish 😄

**Comment by b1zzu** [comment]
@darahayes I've updated it

**Pull request merged**
